# Generated by Django 3.0.4 on 2020-03-19 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('vehicleType', models.CharField(max_length=50)),
                ('yearOfRegistration', models.IntegerField()),
                ('gearBox', models.CharField(max_length=6)),
                ('power', models.IntegerField()),
                ('model', models.CharField(max_length=50)),
                ('mileage', models.IntegerField()),
                ('fuelType', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=50)),
                ('notRepairedDamage', models.CharField(max_length=3)),
                ('dateCreated', models.DateField()),
                ('city', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
            ],
        ),
    ]
