# Generated by Django 3.0.4 on 2020-03-19 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_dealer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dealer',
        ),
    ]
